# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port Nginx will listen on (usually 80)
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]