version: '3'

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Plants-1337010203
      POSTGRES_USER: msc
      POSTGRES_DB: msc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  msc-app:
    build:
      context: ./msc
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - msc-app
    tty: true

volumes:
  postgres_data: null