version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Plants-1337010203
      POSTGRES_USER: msc
      POSTGRES_DB: msc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  msc-web-app:
    restart: unless-stopped
    image: msc-web-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx-proxy:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - msc-web-app
    tty: true

volumes:
  postgres_data: null