"""add minecraft version table

Revision ID: 05b8ed7117af
Revises: ffeffdf94010
Create Date: 2023-11-06 14:10:44.089770

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05b8ed7117af"
down_revision: Union[str, None] = "ffeffdf94010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "minecraft_version",
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column(
            "type", sa.Enum("RELEASE", "SNAPSHOT", name="versiontype"), nullable=False
        ),
        sa.Column("release_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_index(
        "idx_minecraft_version_is_latest_type",
        "minecraft_version",
        ["is_latest", "type"],
        unique=True,
        postgresql_where=sa.text("is_latest IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_minecraft_version_is_latest_type",
        table_name="minecraft_version",
        postgresql_where=sa.text("is_latest IS true"),
    )
    op.drop_table("minecraft_version")
    # ### end Alembic commands ###
