"""add favicon to server

Revision ID: 0d1664d2c354
Revises: 958e94968158
Create Date: 2023-09-19 22:02:26.822562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1664d2c354'
down_revision: Union[str, None] = '958e94968158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('favicon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'favicon')
    # ### end Alembic commands ###
