"""simplify and secure auction creation

Revision ID: 19bcd782faab
Revises: 7a1785dcaeb3
Create Date: 2023-09-29 16:10:45.839616

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19bcd782faab"
down_revision: Union[str, None] = "7a1785dcaeb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auction", sa.Column("sponsored_year", sa.Integer(), nullable=False))
    op.add_column("auction", sa.Column("sponsored_month", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "auction_unique_sponsored_year_and_month",
        "auction",
        ["sponsored_year", "sponsored_month"],
    )
    op.create_check_constraint(
        "auction_sponsored_starts_at_within_month",
        "auction",
        sa.and_(
            sa.extract("year", sa.column("sponsored_starts_at"))
            == sa.column("sponsored_year"),
            sa.extract("month", sa.column("sponsored_starts_at"))
            == sa.column("sponsored_month"),
        ),
    )
    op.create_check_constraint(
        "auction_sponsored_ends_at_within_month",
        "auction",
        sa.and_(
            sa.extract("year", sa.column("sponsored_ends_at"))
            == sa.column("sponsored_year"),
            sa.extract("month", sa.column("sponsored_ends_at"))
            == sa.column("sponsored_month"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auction_sponsored_ends_at_within_month", "auction", type_="check"
    )
    op.drop_constraint(
        "auction_sponsored_starts_at_within_month", "auction", type_="check"
    )
    op.drop_constraint(
        "auction_unique_sponsored_year_and_month", "auction", type_="unique"
    )
    op.drop_column("auction", "sponsored_month")
    op.drop_column("auction", "sponsored_year")
    # ### end Alembic commands ###
