"""add banner filetype

Revision ID: 28946b6f137a
Revises: cf7ef8c76001
Create Date: 2023-09-23 21:42:02.378131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28946b6f137a"
down_revision: Union[str, None] = "cf7ef8c76001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("banner_filetype", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "banner_filetype")
    # ### end Alembic commands ###
