"""one bid per server

Revision ID: 2c697ceba394
Revises: 33184a24083a
Create Date: 2023-10-15 21:39:31.988258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c697ceba394"
down_revision: Union[str, None] = "33184a24083a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auction_bid", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_unique_constraint(
        "auction_bid_unique_auction_id_server_id",
        "auction_bid",
        ["auction_id", "server_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auction_bid_unique_auction_id_server_id", "auction_bid", type_="unique"
    )
    op.drop_column("auction_bid", "updated_at")
    # ### end Alembic commands ###
