"""update sponsored table

Revision ID: 33184a24083a
Revises: cad777ec0c35
Create Date: 2023-10-14 20:43:54.571218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33184a24083a"
down_revision: Union[str, None] = "cad777ec0c35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor", sa.Column("year", sa.Integer(), nullable=False))
    op.add_column("sponsor", sa.Column("month", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "sponsor_unique_slot_year_month", "sponsor", ["slot", "year", "month"]
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "sponsor_slot_greater_than_zero",
        "sponsor",
        sa.column("slot") > 0,
    )

    op.create_check_constraint(
        "sponsor_slot_less_than_or_equal_to_ten",
        "sponsor",
        sa.column("slot") <= 10,
    )

    op.create_check_constraint(
        "auction_sponsored_slots_less_than_or_equal_to_ten",
        "auction",
        sa.column("sponsored_slots") <= 10,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sponsor_unique_slot_year_month", "sponsor", type_="unique")
    op.drop_column("sponsor", "month")
    op.drop_column("sponsor", "year")
    # ### end Alembic commands ###

    op.drop_constraint("sponsor_slot_greater_than_zero", "sponsor", type_="check")

    op.drop_constraint(
        "sponsor_slot_less_than_or_equal_to_ten", "sponsor", type_="check"
    )

    op.drop_constraint(
        "auction_sponsored_slots_less_than_or_equal_to_ten",
        "auction",
        type_="check",
    )
