"""Add search index

Revision ID: 714e71c98090
Revises: b79cf7b79c42
Create Date: 2023-10-04 15:57:30.030189

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm, text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "714e71c98090"
down_revision: Union[str, None] = "b79cf7b79c42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("search_index", postgresql.TSVECTOR(), nullable=True)
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(
        text(
            """
            UPDATE server
            SET search_index = to_tsvector('english', name || ' ' || description)
        """
        )
    )
    session.commit()
    session.close()

    op.alter_column("server", "search_index", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "search_index")
    # ### end Alembic commands ###
