"""add is_current_auction

Revision ID: 7a1785dcaeb3
Revises: 78fe2f0a8299
Create Date: 2023-09-29 00:35:42.717270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a1785dcaeb3"
down_revision: Union[str, None] = "78fe2f0a8299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auction", sa.Column("is_current_auction", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "idx_current_auction",
        "auction",
        ["is_current_auction"],
        unique=True,
        postgresql_where=sa.text("is_current_auction IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_current_auction",
        table_name="auction",
        postgresql_where=sa.text("is_current_auction IS true"),
    )
    op.drop_column("auction", "is_current_auction")
    # ### end Alembic commands ###
