"""Add uptime & vote_history table

Revision ID: 7bf67b7be656
Revises: 02df7d5d6116
Create Date: 2023-10-02 00:59:52.447991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, orm


# revision identifiers, used by Alembic.
revision: str = "7bf67b7be656"
down_revision: Union[str, None] = "02df7d5d6116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vote_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("new_vote_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", name="unique_vote_history_id"),
    )
    op.add_column("server", sa.Column("uptime", sa.Float(), nullable=True))

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.execute(text("UPDATE server SET uptime = 100.0"))

    session.commit()
    session.close()

    op.alter_column("server", "uptime", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "uptime")
    op.drop_table("vote_history")
    # ### end Alembic commands ###
