"""add client_ip to vote table

Revision ID: 958e94968158
Revises: c8c3879f8de2
Create Date: 2023-09-13 11:30:01.269777

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "958e94968158"
down_revision: Union[str, None] = "c8c3879f8de2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vote", sa.Column("client_ip_address", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vote", "client_ip_address")
    # ### end Alembic commands ###
