"""add deletion flag to server table

Revision ID: 9c2e8ff53760
Revises: 19bcd782faab
Create Date: 2023-10-01 19:41:13.049047

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c2e8ff53760"
down_revision: Union[str, None] = "19bcd782faab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("flagged_for_deletion", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "server", sa.Column("flagged_for_deletion_at", sa.DateTime(), nullable=True)
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.execute(text("UPDATE server SET flagged_for_deletion = false"))

    session.commit()
    session.close()

    op.alter_column(
        "server",
        "flagged_for_deletion",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "flagged_for_deletion_at")
    op.drop_column("server", "flagged_for_deletion")
    # ### end Alembic commands ###
