"""add video and owner_name

Revision ID: b9d749883f85
Revises: e7f6ee85f3b6
Create Date: 2023-09-27 00:43:25.654308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9d749883f85"
down_revision: Union[str, None] = "e7f6ee85f3b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("video_url", sa.Text(), nullable=True))
    op.add_column("server", sa.Column("owner_name", sa.Text(), nullable=True))
    op.alter_column("server", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("server", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("server", "owner_name")
    op.drop_column("server", "video_url")
    # ### end Alembic commands ###
