"""create Vote and User tables

Revision ID: c8c3879f8de2
Revises: 8ce723b0a06b
Create Date: 2023-09-13 10:05:38.455420

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8c3879f8de2"
down_revision: Union[str, None] = "8ce723b0a06b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Delete server records
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(text("DELETE FROM server"))
    session.commit()
    session.close()

    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", name="unique_user_id"),
    )

    op.create_table(
        "vote",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", name="unique_vote_id"),
    )

    op.add_column("server", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_unique_constraint("unique_server_id", "server", ["id"])
    op.create_foreign_key(
        None, "server", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "server", type_="foreignkey")
    op.drop_constraint("unique_server_id", "server", type_="unique")
    op.drop_column("server", "user_id")
    op.drop_table("vote")
    op.drop_table("user")
    # ### end Alembic commands ###
