"""delete gameplay table

Revision ID: cad777ec0c35
Revises: cc860a174a64
Create Date: 2023-10-13 14:10:36.359106

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cad777ec0c35"
down_revision: Union[str, None] = "cc860a174a64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("server_gameplay")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_gameplay",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("server_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
            name="server_gameplay_server_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="unique_server_gameplay_id"),
    )
    # ### end Alembic commands ###
