"""add web_store

Revision ID: cb51bb611dcb
Revises: b9d749883f85
Create Date: 2023-09-27 00:45:58.000874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb51bb611dcb"
down_revision: Union[str, None] = "b9d749883f85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("web_store", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "web_store")
    # ### end Alembic commands ###
