"""Add minecraft username to vote table

Revision ID: cc860a174a64
Revises: e0d3e5870268
Create Date: 2023-10-10 00:47:22.042695

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc860a174a64"
down_revision: Union[str, None] = "e0d3e5870268"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vote", sa.Column("minecraft_username", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.execute(text("UPDATE vote SET minecraft_username = 'test'"))

    session.commit()
    session.close()

    op.alter_column("vote", "minecraft_username", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vote", "minecraft_username")
    # ### end Alembic commands ###
