"""add banner and icon checksum

Revision ID: cf7ef8c76001
Revises: 826cea83ee0f
Create Date: 2023-09-23 21:21:56.179346

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf7ef8c76001"
down_revision: Union[str, None] = "826cea83ee0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("banner_checksum", sa.Text(), nullable=True))
    op.add_column("server", sa.Column("icon_checksum", sa.Text(), nullable=True))
    op.drop_column("server", "icon_url")
    op.drop_column("server", "favicon")
    op.drop_column("server", "banner_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("banner_url", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "server", sa.Column("favicon", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "server", sa.Column("icon_url", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("server", "icon_checksum")
    op.drop_column("server", "banner_checksum")
    # ### end Alembic commands ###
