"""add payment status

Revision ID: d14aa912d23f
Revises: 2c697ceba394
Create Date: 2023-10-16 23:30:05.480851

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d14aa912d23f"
down_revision: Union[str, None] = "2c697ceba394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auction_bid", sa.Column("payment_status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auction_bid", "payment_status")
    # ### end Alembic commands ###
