"""add uptime to server_history

Revision ID: d2a9fe23bc2e
Revises: 1f0572bacc66
Create Date: 2023-10-03 00:57:50.969677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, text


# revision identifiers, used by Alembic.
revision: str = "d2a9fe23bc2e"
down_revision: Union[str, None] = "1f0572bacc66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server_history", sa.Column("uptime", sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.execute(text("UPDATE server_history SET uptime = 100"))

    session.commit()
    session.close()

    op.alter_column("server_history", "uptime", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server_history", "uptime")
    # ### end Alembic commands ###
