"""Update server table

Revision ID: e0d3e5870268
Revises: 44f8dbbdb176
Create Date: 2023-10-09 22:43:04.669121

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0d3e5870268"
down_revision: Union[str, None] = "44f8dbbdb176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("use_votifier", sa.Boolean(), nullable=True))
    op.alter_column(
        "server", "minecraft_version", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.execute(text("UPDATE server SET use_votifier = false"))

    session.commit()
    session.close()

    op.alter_column(
        "server", "use_votifier", existing_type=sa.BOOLEAN(), nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server", "minecraft_version", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("server", "use_votifier")
    # ### end Alembic commands ###
