"""add last_pinged_at to server

Revision ID: e7f6ee85f3b6
Revises: 28946b6f137a
Create Date: 2023-09-25 14:02:24.006246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7f6ee85f3b6"
down_revision: Union[str, None] = "28946b6f137a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("last_pinged_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "last_pinged_at")
    # ### end Alembic commands ###
