"""add icon url to server

Revision ID: f17da69eab2d
Revises: 54750c4a85e0
Create Date: 2023-09-22 22:57:12.825285

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f17da69eab2d"
down_revision: Union[str, None] = "54750c4a85e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("server", sa.Column("icon_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "icon_url")
    # ### end Alembic commands ###
