"""make bid amount unique

Revision ID: ffeffdf94010
Revises: d14aa912d23f
Create Date: 2023-10-21 15:29:18.053114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffeffdf94010"
down_revision: Union[str, None] = "d14aa912d23f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "auction_bid_unique_auction_id_amount", "auction_bid", ["auction_id", "amount"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auction_bid_unique_auction_id_amount", "auction_bid", type_="unique"
    )
    # ### end Alembic commands ###
